apiVersion: rp5.reportportal.io/v1alpha1
kind: ReportPortal
metadata:
  name: example-reportportal
spec:
  # You cluster default router hostname
  app_domain: apps.test-example.com
  ui_replicas: 1
  api_replicas: 1
  api_image: quay.io/waynesun09/service-api:5.2.2-rootless
  uat_image: reportportal/service-authorization:5.2.1
  index_replicas: 1
  gateway_replicas: 1
  enable_pg_restic_backup: yes
  pg_restic_s3_bucket_init: yes
  pg_s3_bucket_name: pgbackup-123123
  pg_restic_password: rp_user
